# GitLeaks configuration file
title = "GitLeaks Configuration for Chat Bot Project"

[extend]
# Extend default configuration
useDefault = true

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(api[_-]?key|apikey)['"]*\s*[=:]\s*['"][a-zA-Z0-9_\-]{20,}['"]'''
tags = ["key", "API"]

[[rules]]
description = "Google API Key"
id = "google-api-key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["key", "Google"]

# Allowlist for false positives
[[allowlist]]
description = "Environment template files"
paths = [
    '''^\.env\.template$''',
    '''^\.env\.example$''',
]

[[allowlist]]
description = "Ignore test fixtures"
paths = [
    '''.*test.*''',
    '''.*spec.*''',
    '''.*mock.*''',
]

# Note: .env.local should be in .gitignore and not committed
# If you need to whitelist it temporarily, uncomment below:
# [[allowlist]]
# description = "Local environment file (should not be committed)"
# paths = [
#     '''^\.env\.local$''',
# ]