'use client'

import { useMemo, useState } from 'react'
import { Widget } from '@/types/gemini'
import {
  fetchWidgetsFromGemini,
  localGenerateWidgets,
  updateWidgetsWithGemini,
} from '@/services/gemini'
import GeneratedWidget, { Mode } from '@/components/simulate/GeneratedWidget'
import logger from '@/utils/logger'

export default function Page() {
  const [mode, setMode] = useState<Mode>('beginner')
  const [device, setDevice] = useState<'desktop' | 'mobile'>('desktop')
  const [theme, setTheme] = useState<'dark' | 'light'>('dark')
  const [prompt, setPrompt] = useState<string>(
    'Create a dashboard for support tickets with a chart and a list.'
  )
  const [widgets, setWidgets] = useState<Widget[]>(
    localGenerateWidgets(
      'Create a dashboard for support tickets with a chart and a list.'
    )
  )
  const [activity, setActivity] = useState<string[]>([
    'AG-UI initialized with default generated dashboard.',
  ])

  const [updatePrompt, setUpdatePrompt] = useState<string>('')

  const [useGemini, setUseGemini] = useState<boolean>(true)
  const [loading, setLoading] = useState<boolean>(false)

  const containerClasses =
    theme === 'dark'
      ? 'bg-slate-900 text-slate-50'
      : 'bg-slate-50 text-slate-900'

  const panelClasses =
    theme === 'dark'
      ? 'bg-slate-800 text-slate-50 border-slate-700'
      : 'bg-white text-slate-900 border-slate-200'

  const adaptiveHints = useMemo(() => {
    const hints: string[] = []
    if (mode === 'beginner') {
      hints.push('Showing simplified layout with guided explanations.')
    } else {
      hints.push('Showing compact layout with more controls.')
    }

    if (device === 'mobile') {
      hints.push(
        'Optimized for mobile: single-column layout and larger tap targets.'
      )
    } else {
      hints.push(
        'Optimized for desktop: multi-column grid and dense information.'
      )
    }

    if (useGemini) {
      hints.push('Layout is generated by Gemini via /api/gemini-layout.')
    } else {
      hints.push('Layout is generated locally (no external AI call).')
    }

    return hints
  }, [mode, device, useGemini])

  async function handleGenerate() {
    setLoading(true)
    try {
      let newWidgets: Widget[]
      if (useGemini) {
        newWidgets = await fetchWidgetsFromGemini(prompt)
        setActivity(prev => [
          `Gemini generated layout from prompt: "${prompt}"`,
          ...prev.slice(0, 4),
        ])
      } else {
        newWidgets = localGenerateWidgets(prompt)
        setActivity(prev => [
          `Local layout engine generated layout from prompt: "${prompt}"`,
          ...prev.slice(0, 4),
        ])
      }
      setWidgets(newWidgets)
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (err: any) {
      console.error(err)
      setActivity(prev => [
        `Error generating layout (fallback to local): ${err?.message ?? 'Unknown'}`,
        ...prev.slice(0, 4),
      ])
      setWidgets(localGenerateWidgets(prompt))
    } finally {
      setLoading(false)
    }
  }

  async function handleAIUpdate() {
    if (!updatePrompt.trim()) return
    setLoading(true)
    try {
      const updated = await updateWidgetsWithGemini(widgets, updatePrompt)
      setWidgets(updated)
      setActivity(prev => [
        `Gemini UPDATED UI with prompt: "${updatePrompt}"`,
        ...prev.slice(0, 5),
      ])
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (err: any) {
      logger.error(err)
      setActivity(prev => [
        `AI update failed: ${err?.message ?? 'Unknown'}`,
        ...prev.slice(0, 5),
      ])
    } finally {
      setLoading(false)
    }
  }

  function simulateMcpCall(toolName: string) {
    setActivity(prev => [
      `Simulated MCP call → ${toolName}()`,
      ...prev.slice(0, 4),
    ])
  }

  const layoutCols =
    device === 'mobile' ? 'grid-cols-1' : 'grid-cols-2 lg:grid-cols-3'

  return (
    <div className={containerClasses + ' min-h-screen'}>
      <div className="max-w-6xl mx-auto px-4 py-6 space-y-4">
        {/* Header */}
        <header className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">
              AG-UI + Gemini Demo
            </h1>
            <p className="text-sm opacity-80">
              Adaptive & Generative UI (front-end) with Gemini backend and
              simulated MCP tools.
            </p>
          </div>
          <div className="flex flex-wrap gap-2 text-sm">
            <span className="px-2 py-1 rounded-full bg-emerald-500/10 text-emerald-300 border border-emerald-500/30">
              AG-UI
            </span>
            <span className="px-2 py-1 rounded-full bg-indigo-500/10 text-indigo-300 border border-indigo-500/30">
              Gemini
            </span>
            <span className="px-2 py-1 rounded-full bg-sky-500/10 text-sky-300 border border-sky-500/30">
              MCP (simulated)
            </span>
          </div>
        </header>

        {/* Main layout */}
        <div className="grid gap-4 md:grid-cols-[minmax(0,1.1fr)_minmax(0,1.4fr)]">
          {/* Left: Controls */}
          <section
            className={
              panelClasses + ' border rounded-2xl p-4 space-y-4 shadow-sm'
            }
          >
            <h2 className="text-sm font-semibold uppercase tracking-wide opacity-80">
              AG-UI Controls
            </h2>

            {/* Mode & Device */}
            <div className="grid gap-3 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-xs font-medium opacity-80">
                  User Mode
                </label>
                <div className="flex gap-2">
                  <button
                    onClick={() => setMode('beginner')}
                    className={
                      'flex-1 text-xs px-3 py-2 rounded-xl border ' +
                      (mode === 'beginner'
                        ? 'border-emerald-400 bg-emerald-500/10'
                        : 'border-transparent opacity-70 hover:border-slate-500')
                    }
                  >
                    Beginner
                  </button>
                  <button
                    onClick={() => setMode('expert')}
                    className={
                      'flex-1 text-xs px-3 py-2 rounded-xl border ' +
                      (mode === 'expert'
                        ? 'border-emerald-400 bg-emerald-500/10'
                        : 'border-transparent opacity-70 hover:border-slate-500')
                    }
                  >
                    Expert
                  </button>
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-xs font-medium opacity-80">
                  Device Context
                </label>
                <div className="flex gap-2">
                  <button
                    onClick={() => setDevice('desktop')}
                    className={
                      'flex-1 text-xs px-3 py-2 rounded-xl border ' +
                      (device === 'desktop'
                        ? 'border-sky-400 bg-sky-500/10'
                        : 'border-transparent opacity-70 hover:border-slate-500')
                    }
                  >
                    Desktop
                  </button>
                  <button
                    onClick={() => setDevice('mobile')}
                    className={
                      'flex-1 text-xs px-3 py-2 rounded-xl border ' +
                      (device === 'mobile'
                        ? 'border-sky-400 bg-sky-500/10'
                        : 'border-transparent opacity-70 hover:border-slate-500')
                    }
                  >
                    Mobile
                  </button>
                </div>
              </div>
            </div>

            {/* Theme toggle */}
            <div className="space-y-1">
              <label className="text-xs font-medium opacity-80">Theme</label>
              <div className="flex gap-2">
                <button
                  onClick={() => setTheme('dark')}
                  className={
                    'flex-1 text-xs px-3 py-2 rounded-xl border ' +
                    (theme === 'dark'
                      ? 'border-slate-300 bg-slate-800'
                      : 'border-transparent opacity-70 hover:border-slate-500')
                  }
                >
                  Dark
                </button>
                <button
                  onClick={() => setTheme('light')}
                  className={
                    'flex-1 text-xs px-3 py-2 rounded-xl border ' +
                    (theme === 'light'
                      ? 'border-slate-400 bg-slate-100 text-slate-900'
                      : 'border-transparent opacity-70 hover:border-slate-500')
                  }
                >
                  Light
                </button>
              </div>
            </div>

            {/* Gemini toggle */}
            <div className="flex items-center justify-between text-xs border border-dashed rounded-xl px-3 py-2 border-slate-600/60">
              <span className="font-medium">Use Gemini for layout</span>
              <label className="inline-flex items-center gap-2 cursor-pointer">
                <span className="text-[10px] opacity-70">
                  {useGemini ? 'ON' : 'OFF'}
                </span>
                <input
                  type="checkbox"
                  className="hidden"
                  checked={useGemini}
                  onChange={e => setUseGemini(e.target.checked)}
                />
                <span
                  className={
                    'w-9 h-5 flex items-center rounded-full px-0.5 ' +
                    (useGemini ? 'bg-emerald-500' : 'bg-slate-500')
                  }
                >
                  <span
                    className={
                      'w-4 h-4 bg-white rounded-full transform transition-transform ' +
                      (useGemini ? 'translate-x-4' : 'translate-x-0')
                    }
                  ></span>
                </span>
              </label>
            </div>

            {/* Adaptive hints */}
            <div className="text-xs rounded-xl border border-dashed border-slate-500/50 px-3 py-2 opacity-80">
              <p className="font-medium mb-1">Adaptive Behavior:</p>
              <ul className="list-disc list-inside space-y-0.5">
                {adaptiveHints.map((hint, idx) => (
                  <li key={idx}>{hint}</li>
                ))}
              </ul>
            </div>

            {/* Prompt input */}
            <div className="space-y-1">
              <label className="text-xs font-medium opacity-80">
                Describe the UI you want (AG-UI prompt)
              </label>
              <textarea
                rows={4}
                className={
                  'w-full text-xs rounded-xl border px-3 py-2 resize-none bg-transparent outline-none ' +
                  (theme === 'dark'
                    ? 'border-slate-600 focus:border-emerald-400'
                    : 'border-slate-300 focus:border-emerald-500')
                }
                value={prompt}
                onChange={e => setPrompt(e.target.value)}
                placeholder="Example: Create a dashboard for tickets with a chart and a list..."
              />
              <div className="flex justify-between items-center">
                <button
                  onClick={handleGenerate}
                  disabled={loading}
                  className="inline-flex items-center gap-1 text-xs font-medium px-3 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 disabled:opacity-60 disabled:cursor-not-allowed text-slate-900 shadow-sm"
                >
                  {loading ? 'Generating...' : 'Generate Layout'}
                </button>
                <span className="text-[10px] opacity-60">
                  {useGemini
                    ? 'Calls Gemini via /api/gemini-layout.'
                    : 'Uses local layout engine (no external AI).'}
                </span>
              </div>
            </div>

            {/* AI Update Existing UI */}
            <div className="space-y-1 border-t border-slate-600/60 pt-3 mt-3">
              <label className="text-xs font-medium opacity-80">
                Update existing UI with AI (UI-state aware)
              </label>
              <input
                type="text"
                value={updatePrompt}
                onChange={e => setUpdatePrompt(e.target.value)}
                className={
                  'w-full text-xs rounded-xl border px-3 py-2 bg-transparent outline-none ' +
                  (theme === 'dark'
                    ? 'border-slate-600 focus:border-indigo-400'
                    : 'border-slate-300 focus:border-indigo-500')
                }
                placeholder='Example: "Add a Priority column to the table", "Make the chart bigger"...'
              />
              <button
                onClick={handleAIUpdate}
                disabled={loading || !updatePrompt.trim()}
                className="inline-flex items-center gap-1 text-xs font-medium px-3 py-2 rounded-xl bg-indigo-500 hover:bg-indigo-400 disabled:opacity-60 disabled:cursor-not-allowed text-slate-900 shadow-sm"
              >
                {loading ? 'Updating...' : 'Update UI with AI'}
              </button>
              <p className="text-[10px] opacity-60">
                This sends the <strong>current UI state</strong> + your
                instruction to Gemini, then renders the updated UI.
              </p>
            </div>

            {/* Simulated MCP tools */}
            <div className="space-y-1 border-t border-slate-600/60 pt-3 mt-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-medium opacity-80">
                  MCP Tools (simulated)
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded-full border border-slate-500/60 opacity-70">
                  Backend capability layer
                </span>
              </div>
              <div className="flex flex-wrap gap-2 text-xs">
                <button
                  onClick={() => simulateMcpCall('getOpenTickets')}
                  className="px-2.5 py-1 rounded-xl border border-slate-600 hover:border-emerald-400"
                >
                  getOpenTickets()
                </button>
                <button
                  onClick={() => simulateMcpCall('getKpiSummary')}
                  className="px-2.5 py-1 rounded-xl border border-slate-600 hover:border-emerald-400"
                >
                  getKpiSummary()
                </button>
                <button
                  onClick={() => simulateMcpCall('exportDashboard')}
                  className="px-2.5 py-1 rounded-xl border border-slate-600 hover:border-emerald-400"
                >
                  exportDashboard()
                </button>
              </div>
            </div>
          </section>

          {/* Right: Generated UI */}
          <section className="space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-semibold uppercase tracking-wide opacity-80">
                Generated Interface (AG-UI)
              </h2>
              <span className="text-[10px] opacity-60">
                Structure changes based on your prompt + context.
              </span>
            </div>

            <div className={`grid gap-3 ${layoutCols}`}>
              {widgets.map(w => (
                <GeneratedWidget
                  key={w.id}
                  widget={w}
                  panelClasses={panelClasses}
                  mode={mode}
                />
              ))}
            </div>

            {/* Activity log */}
            <div
              className={
                panelClasses + ' border rounded-2xl p-3 text-xs space-y-1'
              }
            >
              <div className="flex justify-between items-center">
                <span className="font-semibold">Activity Log</span>
                <span className="text-[10px] opacity-60">
                  AG-UI + Gemini + MCP events
                </span>
              </div>
              <ul className="space-y-0.5 max-h-28 overflow-y-auto pr-1">
                {activity.map((line, idx) => (
                  <li key={idx} className="opacity-80">
                    • {line}
                  </li>
                ))}
              </ul>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}
